/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppUpdateDialog: typeof import('./../components/ui/AppUpdateDialog.vue')['default']
    AuthAlertDialog: typeof import('./../components/common/AuthAlertDialog.vue')['default']
    AuthDialog: typeof import('./../components/ui/AuthDialog.vue')['default']
    BackToTopButton: typeof import('./../components/ui/BackToTopButton.vue')['default']
    CardDetailModal: typeof import('./../components/card/CardDetailModal.vue')['default']
    CardInfiniteScrollList: typeof import('./../components/card/CardInfiniteScrollList.vue')['default']
    CardTemplate: typeof import('./../components/card/CardTemplate.vue')['default']
    DeckCard: typeof import('./../components/deck/DeckCard.vue')['default']
    DeckCardList: typeof import('./../components/deck/DeckCardList.vue')['default']
    DeckDetailTemplate: typeof import('./../components/deck/DeckDetailTemplate.vue')['default']
    DeckExportDialog: typeof import('./../components/deck/DeckExportDialog.vue')['default']
    DeckRating: typeof import('./../components/deck/DeckRating.vue')['default']
    DecksGalleryItem: typeof import('./../components/deck/DecksGalleryItem.vue')['default']
    DeckShareImage: typeof import('./../components/deck/DeckShareImage.vue')['default']
    DeckSidebar: typeof import('./../components/ui/DeckSidebar.vue')['default']
    DeckStatsDashboard: typeof import('./../components/deck/DeckStatsDashboard.vue')['default']
    DownloadTextDialog: typeof import('./../components/card/DownloadTextDialog.vue')['default']
    DraggableBottomSheet: typeof import('./../components/ui/DraggableBottomSheet.vue')['default']
    FilterSidebar: typeof import('./../components/ui/FilterSidebar.vue')['default']
    FloatingCardClickModeToggle: typeof import('./../components/ui/FloatingCardClickModeToggle.vue')['default']
    FloatingSearchBar: typeof import('./../components/ui/FloatingSearchBar.vue')['default']
    HomeBackground: typeof import('./../components/common/HomeBackground.vue')['default']
    ImageCropperModal: typeof import('./../components/ui/ImageCropperModal.vue')['default']
    ImageZoomViewer: typeof import('./../components/ui/ImageZoomViewer.vue')['default']
    InsetTabs: typeof import('./../components/ui/InsetTabs.vue')['default']
    LazyCardWrapper: typeof import('./../components/common/LazyCardWrapper.vue')['default']
    LinkedCard: typeof import('./../components/card/LinkedCard.vue')['default']
    MarketCreateDialog: typeof import('./../components/market/MarketCreateDialog.vue')['default']
    MarketListingItem: typeof import('./../components/market/MarketListingItem.vue')['default']
    NoticeDialog: typeof import('./../components/common/NoticeDialog.vue')['default']
    QR: typeof import('./../components/common/QR.js')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SeriesCard: typeof import('./../components/card/SeriesCard.vue')['default']
    SettingsModal: typeof import('./../components/ui/SettingsModal.vue')['default']
    ShareDeckDetail: typeof import('./../components/deck/ShareDeckDetail.vue')['default']
    ShareToGalleryDialog: typeof import('./../components/deck/ShareToGalleryDialog.vue')['default']
    SplashAnimation: typeof import('./../components/common/SplashAnimation.vue')['default']
    SponsorNoticeDialog: typeof import('./../components/ui/SponsorNoticeDialog.vue')['default']
    UserProfileModal: typeof import('./../components/ui/UserProfileModal.vue')['default']
  }
}
