/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'
import type {
  _ExtractParamParserType,
} from 'vue-router/experimental'

declare module 'vue-router' {
  interface TypesConfig {
    ParamParsers:
      | never
    RouteNamedMap: import('vue-router/auto-routes').RouteNamedMap
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    'Home': RouteRecordInfo<
      'Home',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'BanList': RouteRecordInfo<
      'BanList',
      '/banlist',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'Community': RouteRecordInfo<
      'Community',
      '/community',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'DeckLog': RouteRecordInfo<
      'DeckLog',
      '/decklog/:key',
      { key: ParamValue<true> },
      { key: ParamValue<false> },
      | never
    >,
    'Decks': RouteRecordInfo<
      'Decks',
      '/decks',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'DeckDetail': RouteRecordInfo<
      'DeckDetail',
      '/decks/:key',
      { key: ParamValue<true> },
      { key: ParamValue<false> },
      | never
    >,
    'ForgotPassword': RouteRecordInfo<
      'ForgotPassword',
      '/forgot-password',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'DecksGallery': RouteRecordInfo<
      'DecksGallery',
      '/gallery',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'Market': RouteRecordInfo<
      'Market',
      '/market',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'ResetPassword': RouteRecordInfo<
      'ResetPassword',
      '/reset-password',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'GlobalSearch': RouteRecordInfo<
      'GlobalSearch',
      '/search/:game',
      { game: ParamValue<true> },
      { game: ParamValue<false> },
      | never
    >,
    'SeriesCardTable': RouteRecordInfo<
      'SeriesCardTable',
      '/series',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'SeriesDetail': RouteRecordInfo<
      'SeriesDetail',
      '/series/:seriesId',
      { seriesId: ParamValue<true> },
      { seriesId: ParamValue<false> },
      | never
    >,
    'ShareDeckDetail': RouteRecordInfo<
      'ShareDeckDetail',
      '/share-decks/:key',
      { key: ParamValue<true> },
      { key: ParamValue<false> },
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | 'Home'
      views:
        | never
    }
    'src/pages/banlist/index.vue': {
      routes:
        | 'BanList'
      views:
        | never
    }
    'src/pages/community/index.vue': {
      routes:
        | 'Community'
      views:
        | never
    }
    'src/pages/decklog/[key].vue': {
      routes:
        | 'DeckLog'
      views:
        | never
    }
    'src/pages/decks/index.vue': {
      routes:
        | 'Decks'
      views:
        | never
    }
    'src/pages/decks/[key].vue': {
      routes:
        | 'DeckDetail'
      views:
        | never
    }
    'src/pages/forgot-password/index.vue': {
      routes:
        | 'ForgotPassword'
      views:
        | never
    }
    'src/pages/gallery/index.vue': {
      routes:
        | 'DecksGallery'
      views:
        | never
    }
    'src/pages/market/index.vue': {
      routes:
        | 'Market'
      views:
        | never
    }
    'src/pages/reset-password/index.vue': {
      routes:
        | 'ResetPassword'
      views:
        | never
    }
    'src/pages/search/[game].vue': {
      routes:
        | 'GlobalSearch'
      views:
        | never
    }
    'src/pages/series/index.vue': {
      routes:
        | 'SeriesCardTable'
      views:
        | never
    }
    'src/pages/series/[seriesId].vue': {
      routes:
        | 'SeriesDetail'
      views:
        | never
    }
    'src/pages/share-decks/[key].vue': {
      routes:
        | 'ShareDeckDetail'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
