const wsSeriesMap = {
  'brd': {
    name: '棕色尘埃2',
    prefixes: ['BRD'],
    latestReleaseDate: '2026-07-03',
  },
  'gbf': {
    name: '碧蓝幻想',
    prefixes: ['GBF'],
    latestReleaseDate: '2026-06-26',
  },
  'ga': {
    name: 'GA文库',
    prefixes: [
      'GA01',
      'GA02',
      'GA03',
      'GA04',
      'GA05',
      'GA06',
      'GA07',
      'GA08',
      'GA09',
      'GA10',
      'GA11',
      'GA12',
      'GA13',
      'GA14',
      'GA15',
      'GA16',
      'GA17',
      'GA18',
      'GA19',
    ],
    latestReleaseDate: '2026-06-12',
  },
  'thp': {
    name: '東方Project',
    prefixes: ['THP'],
    latestReleaseDate: '2026-05-30',
  },
  'anm': {
    name: 'anemoi',
    prefixes: ['ANM'],
    latestReleaseDate: '2026-05-01',
  },
  'vrg': {
    name: 'VIRTUAL GIRL',
    prefixes: ['VRG', 'BDY'],
    latestReleaseDate: '2026-03-06',
  },
  'tal': {
    name: '传说系列',
    prefixes: ['TAL'],
    latestReleaseDate: '2026-01-16',
  },
  're0': {
    name: 'Re：从零开始的异世界生活',
    prefixes: ['RZ'],
    latestReleaseDate: '2026-07-24',
  },
  'fantasia': {
    name: '富士见Fantasia文库',
    prefixes: [
      'F35',
      'Fab',
      'Fcr',
      'Fdd',
      'Fdl',
      'Fdy',
      'Ffp',
      'Fgc',
      'Fgi',
      'Fgm',
      'Fhc',
      'Fii',
      'Fil',
      'Fjk',
      'Fkd',
      'Fkk',
      'Fkm',
      'Fkn',
      'Fks',
      'Fkz',
      'Fma',
      'Fmr',
      'Foo',
      'Fos',
      'Foy',
      'Fra',
      'Fsa',
      'Fsh',
      'Fsi',
      'Fsl',
      'Fsp',
      'Fsr',
      'Ftr',
      'Ftt',
      'Fvd',
    ],
    latestReleaseDate: '2024-10-25',
  },
  'persona': {
    name: '女神异闻录',
    prefixes: ['P3', 'P4', 'PQ', 'P5'],
    latestReleaseDate: '2024-05-17',
  },
  'lrc': {
    name: '莉可丽丝',
    prefixes: ['LRC'],
    latestReleaseDate: '2024-11-15',
  },
  'gbc': {
    name: '少女乐队的呐喊',
    prefixes: ['GCR'],
    latestReleaseDate: '2025-02-28',
  },
  'ctb': {
    name: '足球小将',
    prefixes: ['CTB'],
    latestReleaseDate: '2024-09-13',
  },
  'cs': {
    name: '蜡笔小新',
    prefixes: ['CS'],
    latestReleaseDate: '2024-07-26',
  },
  'yrc': {
    name: '摇曳露营',
    prefixes: ['YRC'],
    latestReleaseDate: '2024-11-08',
  },
  'rsk': {
    name: '里世界郊游',
    prefixes: ['RSK'],
    latestReleaseDate: '2024-01-19',
  },
  'bd': {
    name: 'BanG Dream!',
    prefixes: ['BD', 'BDY'],
    latestReleaseDate: '2026-03-06',
  },
  'amg': {
    name: '缘结甘神家',
    prefixes: ['AMG'],
    latestReleaseDate: '2025-04-18',
  },
  'pjs': {
    name: '世界计划多彩舞台 feat. 初音未来',
    prefixes: ['PJS'],
    latestReleaseDate: '2025-12-26',
  },
  'aoh': {
    name: '青桐高校',
    prefixes: ['AOH'],
    latestReleaseDate: '2025-06-13',
  },
  'lhs': {
    name: 'Love Live! 莲之空女学院学园偶像俱乐部',
    prefixes: ['LHS'],
    latestReleaseDate: '2025-01-31',
  },
  'imc': {
    name: '偶像大师 灰姑娘女孩',
    prefixes: ['IMC'],
    latestReleaseDate: '2026-07-18',
  },
  'ab': {
    name: 'Angel Beats!／Kud Wafter',
    prefixes: ['AB', 'KW', 'Kab', 'Hab', 'Kkw'],
    latestReleaseDate: '2014-06-27',
  },
  'cn': {
    name: 'CANAAN',
    prefixes: ['CN'],
    latestReleaseDate: '2009-08-27',
  },
  'cl': {
    name: 'CLANNAD',
    prefixes: ['CL', 'Kcl', 'Kta'],
    latestReleaseDate: '2016-04-08',
  },
  'pxr': {
    name: 'PIXAR',
    prefixes: ['PXR', 'Dpx', 'MRp'],
    latestReleaseDate: '2025-08-01',
  },
  'cha': {
    name: 'Charlotte',
    prefixes: ['CHA', 'Kch'],
    latestReleaseDate: '2015-10-30',
  },
  'dc': {
    name: '初音岛',
    prefixes: ['DC', 'DC3', 'DC4', 'DS', 'DC5'],
    latestReleaseDate: '2026-03-13',
  },
  'dj': {
    name: 'D4DJ',
    prefixes: ['DJ'],
    latestReleaseDate: '2023-04-21',
  },
  'fxx': {
    name: 'DARLING in the FRANXX',
    prefixes: ['FXX'],
    latestReleaseDate: '2018-09-21',
  },
  'dal': {
    name: '约会大作战',
    prefixes: ['DAL', 'Fdl'],
    latestReleaseDate: '2025-10-03',
  },
  'dd': {
    name: 'DOG DAYS',
    prefixes: ['DD'],
    latestReleaseDate: '2015-11-13',
  },
  'dct': {
    name: 'D_CIDE TRAUMEREI',
    prefixes: ['DCT'],
    latestReleaseDate: '2022-04-29',
  },
  'dds': {
    name: 'Disney',
    prefixes: ['Dds', 'MRd'],
    latestReleaseDate: '2024-05-24',
  },
  'dds100': {
    name: 'Disney100',
    prefixes: ['Dmv', 'Dsw', 'Dpx', 'Dds'],
    latestReleaseDate: '2023-04-07',
  },
  'fate': {
    name: 'Fate',
    prefixes: ['FS', 'FU', 'FH', 'FZ'],
    latestReleaseDate: '2020-12-04',
  },
  'apo': {
    name: 'Fate/Apocrypha',
    prefixes: ['APO'],
    latestReleaseDate: '2018-05-25',
  },
  'fgo': {
    name: 'Fate/Grand Order',
    prefixes: ['FGO'],
    latestReleaseDate: '2021-10-29',
  },
  'hol': {
    name: 'Hololive',
    prefixes: ['HOL'],
    latestReleaseDate: '2024-09-06',
  },
  'jj': {
    name: 'JOJO的奇妙冒险',
    prefixes: ['JJ'],
    latestReleaseDate: '2023-08-11',
  },
  'key': {
    name: 'Key',
    prefixes: [
      'Kab',
      'Kai',
      'Kch',
      'Kcl',
      'Kdb',
      'Key',
      'Khb',
      'Kka',
      'Klb',
      'Krw',
      'Ksm',
      'Kkw',
      'Kta',
    ],
    latestReleaseDate: '2025-11-07',
  },
  'lb': {
    name: 'Little Busters!',
    prefixes: ['LB', 'KW', 'Klb'],
    latestReleaseDate: '2021-10-15',
  },
  'mde': {
    name: '超时空要塞',
    prefixes: ['MF', 'MDE'],
    latestReleaseDate: '2024-01-25',
  },
  'lod': {
    name: 'Lost Decade',
    prefixes: ['LOD'],
    latestReleaseDate: '2020-06-05',
  },
  'll': {
    name: 'Love Live!',
    prefixes: ['LL', 'LSF', 'SIL'],
    latestReleaseDate: '2023-10-27',
  },
  'lls': {
    name: 'Love Live! Sunshine!!',
    prefixes: ['LSS', 'LSF', 'SIS'],
    latestReleaseDate: '2019-08-09',
  },
  'lnj': {
    name: 'Love Live! 虹咲学园学园偶像同好会',
    prefixes: ['LNJ', 'LSF', 'SIN'],
    latestReleaseDate: '2022-05-27',
  },
  'lsp': {
    name: 'Love Live! SuperStar!!',
    prefixes: ['LSP', 'LSF', 'SIP'],
    latestReleaseDate: '2021-12-10',
  },
  'sif': {
    name: 'Love Live! 学园偶像祭2',
    prefixes: ['SIL', 'SIS', 'SIN', 'SIP', 'LSF'],
    latestReleaseDate: '2023-10-27',
  },
  'mar': {
    name: 'MARVEL',
    prefixes: ['MAR', 'Dmv'],
    latestReleaseDate: '2025-09-19',
  },
  'mb': {
    name: 'MELTY BLOOD／空之境界',
    prefixes: ['MB', 'KK'],
    latestReleaseDate: '2010-11-20',
  },
  'ovl': {
    name: 'Overlord',
    prefixes: ['OVL'],
    latestReleaseDate: '2025-11-28',
  },
  'pt': {
    name: 'Phantom -Requiem for the Phantom-',
    prefixes: ['PT'],
    latestReleaseDate: '2009-10-10',
  },
  'rw': {
    name: 'Rewrite',
    prefixes: ['RW', 'Krw'],
    latestReleaseDate: '2017-01-27',
  },
  'spy': {
    name: 'SPY×FAMILY',
    prefixes: ['SPY'],
    latestReleaseDate: '2023-07-21',
  },
  'zm': {
    name: '零之使魔',
    prefixes: ['ZM'],
    latestReleaseDate: '2012-05-12',
  },
  'nr': {
    name: '魔法少女奈叶',
    prefixes: ['NS', 'N1', 'NV', 'NA', 'N2', 'NR', 'ND', 'NTA'],
    latestReleaseDate: '2025-06-20',
  },
  'ls': {
    name: '幸运☆星',
    prefixes: ['LS'],
    latestReleaseDate: '2009-03-28',
  },
  'sk': {
    name: '穿越宇宙的少女／舞-HiME＆舞-乙HiME',
    prefixes: ['SK', 'MH'],
    latestReleaseDate: '2009-08-27',
  },
  'sy': {
    name: '凉宫春日的忧郁',
    prefixes: ['SY', 'Ssy'],
    latestReleaseDate: '2016-12-23',
  },
  'gid': {
    name: '魔法禁书目录／某科学的超电磁炮',
    prefixes: ['ID', 'RG', 'Gid'],
    latestReleaseDate: '2016-12-23',
  },
  'ss': {
    name: '灼眼的夏娜',
    prefixes: ['SS', 'Gss'],
    latestReleaseDate: '2023-10-20',
  },
  'rn': {
    name: '机器人笔记',
    prefixes: ['RN'],
    latestReleaseDate: '2012-11-24',
  },
  'nj': {
    name: '日常',
    prefixes: ['NJ'],
    latestReleaseDate: '2012-01-14',
  },
  'mr': {
    name: '魔法少女小圆',
    prefixes: ['MM', 'MR'],
    latestReleaseDate: '2020-08-14',
  },
  'sg': {
    name: '战姬绝唱Symphogear',
    prefixes: ['SG'],
    latestReleaseDate: '2021-06-11',
  },
  'vr': {
    name: 'Vividred Operation',
    prefixes: ['VR'],
    latestReleaseDate: '2013-06-29',
  },
  'gt': {
    name: '穿透幻影的太阳',
    prefixes: ['GT'],
    latestReleaseDate: '2013-11-29',
  },
  'nk': {
    name: '伪恋',
    prefixes: ['NK'],
    latestReleaseDate: '2015-08-21',
  },
  'gf': {
    name: '临时女友',
    prefixes: ['GF'],
    latestReleaseDate: '2015-07-24',
  },
  'tl': {
    name: 'To LOVE',
    prefixes: ['TL'],
    latestReleaseDate: '2016-03-11',
  },
  'gu': {
    name: '请问您今天要来点兔子吗？？',
    prefixes: ['GU'],
    latestReleaseDate: '2024-10-11',
  },
  'cgs': {
    name: '卡牌游戏西柚子',
    prefixes: ['CGS', 'SI'],
    latestReleaseDate: '2016-03-25',
  },
  'ks': {
    name: '为美好的世界献上祝福！',
    prefixes: ['KS', 'Sks'],
    latestReleaseDate: '2020-04-24',
  },
  'vs': {
    name: 'ViVid Strike!',
    prefixes: ['VS'],
    latestReleaseDate: '2017-06-23',
  },
  'kmn': {
    name: '兽娘动物园',
    prefixes: ['KMN'],
    latestReleaseDate: '2017-08-25',
  },
  'hll': {
    name: '雏逻辑～from Luck & Logic～',
    prefixes: ['HLL'],
    latestReleaseDate: '2018-01-26',
  },
  'shs': {
    name: '路人女主的养成方法',
    prefixes: ['SHS', 'Fsh'],
    latestReleaseDate: '2022-06-10',
  },
  'smp': {
    name: 'Summer Pockets',
    prefixes: ['SMP', 'Ksm'],
    latestReleaseDate: '2026-04-10',
  },
  'yys': {
    name: '摇曳庄的幽奈小姐',
    prefixes: ['YYS'],
    latestReleaseDate: '2018-12-14',
  },
  'snk': {
    name: '角川Sneaker文库',
    prefixes: [
      'Sak',
      'Sbm',
      'Scn',
      'Sde',
      'Sdy',
      'Seo',
      'Sfl',
      'Shg',
      'Shh',
      'Shm',
      'Sks',
      'Sky',
      'Sle',
      'Sls',
      'Smc',
      'Sme',
      'Smi',
      'Smu',
      'Snk',
      'Snw',
      'Soa',
      'Soj',
      'Srd',
      'Srm',
      'Ssc',
      'Ssh',
      'Ssk',
      'Ssn',
      'Sst',
      'Ssw',
      'Ssy',
      'Stk',
      'Stm',
    ],
    latestReleaseDate: '2025-03-14',
  },
  'sby': {
    name: '青春猪头少年',
    prefixes: ['SBY', 'Gby'],
    latestReleaseDate: '2026-03-27',
  },
  'ccs': {
    name: '魔卡少女樱',
    prefixes: ['CCS'],
    latestReleaseDate: '2024-02-23',
  },
  '5hy': {
    name: '五等分的新娘',
    prefixes: ['5HY'],
    latestReleaseDate: '2024-03-08',
  },
  'knk': {
    name: '租借女友',
    prefixes: ['KNK'],
    latestReleaseDate: '2025-10-31',
  },
  'prd': {
    name: '公主连结！Re:Dive',
    prefixes: ['PRD'],
    latestReleaseDate: '2026-05-02',
  },
  'dbg': {
    name: '成神之日',
    prefixes: ['DBG', 'Kdb'],
    latestReleaseDate: '2021-05-28',
  },
  'zls': {
    name: '佐贺偶像是传奇 卷土重来',
    prefixes: ['ZLS'],
    latestReleaseDate: '2021-11-12',
  },
  'kmd': {
    name: '小林家的龙女仆',
    prefixes: ['KMD'],
    latestReleaseDate: '2022-04-08',
  },
  'hbr': {
    name: '炽焰天穹',
    prefixes: ['HBR', 'Khb', 'Hab'],
    latestReleaseDate: '2024-08-09',
  },
  'uma': {
    name: '赛马娘 Pretty Derby',
    prefixes: ['UMA'],
    latestReleaseDate: '2026-02-13',
  },
  'btr': {
    name: '孤独摇滚',
    prefixes: ['BTR'],
    latestReleaseDate: '2023-09-29',
  },
  'dgk': {
    name: '电击文库',
    prefixes: [
      'G86',
      'Gas',
      'Gaw',
      'Gbb',
      'Gbc',
      'Gbd',
      'Gbl',
      'Gby',
      'Gc3',
      'Gdc',
      'Gdr',
      'Gds',
      'Gdy',
      'Gem',
      'Gfq',
      'Gga',
      'Ggg',
      'Ggh',
      'Ggu',
      'Ghh',
      'Ghm',
      'Gid',
      'Giy',
      'Gkb',
      'Gkl',
      'Gkm',
      'Glt',
      'Gmf',
      'Gmm',
      'Gmr',
      'Gms',
      'Gnh',
      'Gnm',
      'Gns',
      'Gny',
      'Goi',
      'Gok',
      'Gom',
      'Gos',
      'Grk',
      'Gsb',
      'Gsc',
      'Gsd',
      'Gsk',
      'Gso',
      'Gsp',
      'Gsr',
      'Gss',
      'Gtd',
      'Gyf',
    ],
    latestReleaseDate: '2023-09-01',
  },
  'yhn': {
    name: '幻日夜羽 -镜中晖光-',
    prefixes: ['YHN'],
    latestReleaseDate: '2023-11-10',
  },
  'ags': {
    name: '机甲爱丽丝',
    prefixes: ['AGS'],
    latestReleaseDate: '2023-10-13',
  },
  'ayt': {
    name: '妖幻三重奏',
    prefixes: ['AYT'],
    latestReleaseDate: '2023-11-23',
  },
  'bav': {
    name: '碧蓝档案',
    prefixes: ['BAV'],
    latestReleaseDate: '2025-10-24',
  },
  'gim': {
    name: '学园偶像大师',
    prefixes: ['GIM'],
    latestReleaseDate: '2025-05-23',
  },
  'mki': {
    name: '败犬女主太多了！',
    prefixes: ['MKI'],
    latestReleaseDate: '2025-06-27',
  },
  'va': {
    name: 'Visual Arts',
    prefixes: ['VA'],
    latestReleaseDate: '-',
  },
  'dg': {
    name: '魔界战记',
    prefixes: ['DG'],
    latestReleaseDate: '2013-09-13',
  },
  'sr': {
    name: '光明之响',
    prefixes: ['SE', 'SF', 'SR'],
    latestReleaseDate: '2015-07-31',
  },
  'kf': {
    name: 'THE KING OF FIGHTERS',
    prefixes: ['KF'],
    latestReleaseDate: '2023-09-22',
  },
  'sb': {
    name: '战国BASARA',
    prefixes: ['SB'],
    latestReleaseDate: '2010-09-18',
  },
  'im': {
    name: '偶像大师',
    prefixes: ['IM', 'IAS'],
    latestReleaseDate: '2025-07-26',
  },
  'ft': {
    name: '妖精的尾巴',
    prefixes: ['FT'],
    latestReleaseDate: '2025-02-07',
  },
  'mk': {
    name: '侦探歌剧 少女福尔摩斯',
    prefixes: ['MK', 'MK2'],
    latestReleaseDate: '2019-01-28',
  },
  'ev': {
    name: '新世纪福音战士新剧场版',
    prefixes: ['EV'],
    latestReleaseDate: '2010-12-11',
  },
  'br': {
    name: '黑岩射手',
    prefixes: ['BR'],
    latestReleaseDate: '2011-01-22',
  },
  'kg': {
    name: '刀语',
    prefixes: ['KG'],
    latestReleaseDate: '2011-04-02',
  },
  'bm': {
    name: '物语系列',
    prefixes: ['BM', 'NM', 'MG'],
    latestReleaseDate: '2016-01-22',
  },
  'gc': {
    name: '罪恶王冠',
    prefixes: ['GC'],
    latestReleaseDate: '2012-04-07',
  },
  'aw': {
    name: '加速世界',
    prefixes: ['AW', 'Gaw'],
    latestReleaseDate: '2016-09-02',
  },
  'sao': {
    name: '刀剑神域',
    prefixes: ['SAO', 'Gso'],
    latestReleaseDate: '2022-11-18',
  },
  'pd': {
    name: '初音未来 -Project DIVA-',
    prefixes: ['PD'],
    latestReleaseDate: '2017-12-01',
  },
  'pp': {
    name: '心理测量者',
    prefixes: ['PP'],
    latestReleaseDate: '2013-05-18',
  },
  'gg': {
    name: '翠星之加尔刚蒂亚',
    prefixes: ['GG'],
    latestReleaseDate: '2013-08-23',
  },
  'ds2': {
    name: 'TV动画「恶魔幸存者2」',
    prefixes: ['DS2'],
    latestReleaseDate: '2013-10-18',
  },
  'pi': {
    name: '魔法少女伊莉雅',
    prefixes: ['PI'],
    latestReleaseDate: '2021-02-12',
  },
  'woo': {
    name: 'T宝的悲惨日常',
    prefixes: ['Woo'],
    latestReleaseDate: '2014-01-11',
  },
  'klk': {
    name: '斩服少女',
    prefixes: ['KLK'],
    latestReleaseDate: '2016-12-23',
  },
  'lh': {
    name: '记录的地平线',
    prefixes: ['LH'],
    latestReleaseDate: '2016-04-08',
  },
  'kc': {
    name: '舰队Collection',
    prefixes: ['KC'],
    latestReleaseDate: '2019-07-26',
  },
  'gst': {
    name: '超爆裂异次元卡片大战 Gigant Shooter 司',
    prefixes: ['GST'],
    latestReleaseDate: '2014-10-10',
  },
  'tf': {
    name: '火星异种',
    prefixes: ['TF'],
    latestReleaseDate: '2015-02-27',
  },
  'aot': {
    name: '进击的巨人',
    prefixes: ['AOT'],
    latestReleaseDate: '2017-09-29',
  },
  'sgs': {
    name: 'SchoolGirl Strikers',
    prefixes: ['SGS'],
    latestReleaseDate: '2016-02-26',
  },
  'py': {
    name: '噗哟噗哟',
    prefixes: ['PY'],
    latestReleaseDate: '2016-02-04',
  },
  'oms': {
    name: '阿松',
    prefixes: ['OMS'],
    latestReleaseDate: '2016-06-17',
  },
  'kr': {
    name: '境界之轮回',
    prefixes: ['KR'],
    latestReleaseDate: '2016-07-15',
  },
  'ki': {
    name: '羁绊者',
    prefixes: ['KI'],
    latestReleaseDate: '2016-09-30',
  },
  'cc': {
    name: '锁链战记 ～赫克瑟塔斯之光～',
    prefixes: ['CC'],
    latestReleaseDate: '2017-04-28',
  },
  'sw': {
    name: 'STAR WARS',
    prefixes: ['SW', 'Dsw'],
    latestReleaseDate: '2024-08-23',
  },
  'gl': {
    name: '天元突破红莲螺岩',
    prefixes: ['GL'],
    latestReleaseDate: '2018-01-26',
  },
  'gzl': {
    name: '动画电影『GODZILLA』',
    prefixes: ['GZL'],
    latestReleaseDate: '2018-11-09',
  },
  'ggo': {
    name: '刀剑神域外传 Gun Gale Online',
    prefixes: ['GGO', 'Ggg'],
    latestReleaseDate: '2025-03-07',
  },
  'rsl': {
    name: '少女☆歌剧 Revue Starlight',
    prefixes: ['RSL'],
    latestReleaseDate: '2022-10-14',
  },
  'ngl': {
    name: '游戏人生',
    prefixes: ['NGL'],
    latestReleaseDate: '2018-08-03',
  },
  'ims': {
    name: '偶像大师 MILLION LIVE!',
    prefixes: ['IMS', 'IAS'],
    latestReleaseDate: '2026-04-24',
  },
  'stg': {
    name: 'STEINS;GATE',
    prefixes: ['STG'],
    latestReleaseDate: '2018-10-26',
  },
  'gbs': {
    name: '哥布林杀手',
    prefixes: ['GBS', 'GA04'],
    latestReleaseDate: '2019-04-19',
  },
  'tsk': {
    name: '关于我转生变成史莱姆这档事',
    prefixes: ['TSK'],
    latestReleaseDate: '2023-01-20',
  },
  'gri': {
    name: '灰色的果实',
    prefixes: ['GRI'],
    latestReleaseDate: '2024-06-07',
  },
  'all': {
    name: '突击莉莉',
    prefixes: ['ALL'],
    latestReleaseDate: '2026-02-27',
  },
  'skr': {
    name: '新樱花大战',
    prefixes: ['SKR'],
    latestReleaseDate: '2020-05-15',
  },
  'bfr': {
    name: '因为太怕痛就全点防御力了',
    prefixes: ['BFR'],
    latestReleaseDate: '2020-11-20',
  },
  'kgl': {
    name: '辉夜大小姐想让我告白～天才们的恋爱头脑战～',
    prefixes: ['KGL'],
    latestReleaseDate: '2022-07-15',
  },
  'isc': {
    name: '偶像大师 闪耀色彩',
    prefixes: ['ISC'],
    latestReleaseDate: '2025-09-26',
  },
  'mti': {
    name: '无职转生 ~到了异世界就拿出真本事~',
    prefixes: ['MTI'],
    latestReleaseDate: '2021-07-30',
  },
  'wtr': {
    name: '境界触发者',
    prefixes: ['WTR'],
    latestReleaseDate: '2021-10-15',
  },
  'ddm': {
    name: '在地下城寻求邂逅是否搞错了什么',
    prefixes: ['DDM', 'GA10'],
    latestReleaseDate: '2021-11-26',
  },
  'trv': {
    name: '东京复仇者',
    prefixes: ['TRV'],
    latestReleaseDate: '2022-05-13',
  },
  'azl': {
    name: '碧蓝航线',
    prefixes: ['AZL'],
    latestReleaseDate: '2025-01-17',
  },
  'csm': {
    name: '电锯人',
    prefixes: ['CSM'],
    latestReleaseDate: '2023-06-16',
  },
  'ari': {
    name: '平凡职业造就世界最强',
    prefixes: ['ARI'],
    latestReleaseDate: '2023-02-24',
  },
  'pad': {
    name: '智龙迷城',
    prefixes: ['PAD'],
    latestReleaseDate: '2023-05-19',
  },
  'osk': {
    name: '我推的孩子',
    prefixes: ['OSK'],
    latestReleaseDate: '2026-08-07',
  },
  'sfn': {
    name: '葬送的芙莉莲',
    prefixes: ['SFN'],
    latestReleaseDate: '2026-08-28',
  },
  'mrp': {
    name: 'Disney 镜之守卫者',
    prefixes: ['MRd', 'MRp'],
    latestReleaseDate: '2024-05-24',
  },
  'rkn': {
    name: '浪客剑心 -明治剑客浪漫谭-',
    prefixes: ['RKN'],
    latestReleaseDate: '2024-07-12',
  },
  'nik': {
    name: '胜利女神：妮姬',
    prefixes: ['NIK'],
    latestReleaseDate: '2026-09-19',
  },
  'ddd': {
    name: '胆大党',
    prefixes: ['DDD'],
    latestReleaseDate: '2026-05-15',
  },
  'kj8': {
    name: '怪兽8号',
    prefixes: ['KJ8'],
    latestReleaseDate: '2025-08-08',
  },
  'kms': {
    name: '黄金拼图',
    prefixes: ['KMS'],
    latestReleaseDate: '2025-11-14',
  },
  'ws': {
    name: '其他',
    prefixes: ['WS', 'NSO', 'CJ', 'VG'],
    latestReleaseDate: '-',
  },
}

const wsrSeriesMap = {
  os12: {
    name: '拔作岛 THE ANIMATION',
    prefixes: ['OS12'],
    latestReleaseDate: '2026-08-07',
  },
  os11: {
    name: 'Purple software',
    prefixes: ['OS11'],
    latestReleaseDate: '2026-07-03',
  },
  os10: {
    name: 'Navel',
    prefixes: ['OS10'],
    latestReleaseDate: '2026-05-29',
  },
  os09: {
    name: 'ALICESOFT',
    prefixes: ['OS09'],
    latestReleaseDate: '2026-04-17',
  },
  os08: {
    name: 'AQUAPLUS',
    prefixes: ['OS08'],
    latestReleaseDate: '2026-02-27',
  },
  os05: {
    name: 'sprite',
    prefixes: ['OS05'],
    latestReleaseDate: '2025-10-31',
  },
  os04: {
    name: '异种族风俗娘',
    prefixes: ['OS04'],
    latestReleaseDate: '2025-08-29',
  },
  os03: {
    name: 'HARUKAZE',
    prefixes: ['OS03'],
    latestReleaseDate: '2025-06-27',
  },
  os01: {
    name: '柚子社',
    prefixes: ['OS01'],
    latestReleaseDate: '2025-04-25',
  },
  os02: {
    name: '梦想成为魔法少女',
    prefixes: ['OS02'],
    latestReleaseDate: '2025-04-25',
  },
  os06: {
    name: '枕',
    prefixes: ['OS06'],
    latestReleaseDate: '2025-12-26',
  },
  os07: {
    name: 'Lose＆Whisp',
    prefixes: ['OS07'],
    latestReleaseDate: '2026-01-30',
  },
  wsr: {
    name: '其他',
    prefixes: ['OS00', 'WSR'],
    latestReleaseDate: '-',
  },
}

const wscSeriesMap = {
  '[cn]gfl': {
    name: '[cn]少女前线系列',
    prefixes: ['[cn]GFL'],
    latestReleaseDate: '2026-08-07',
  },
  '[cn]p5x': {
    name: '[cn]女神异闻录：夜幕魅影',
    prefixes: ['[cn]P5X'],
    latestReleaseDate: '2026-06-26',
  },
  '[cn]fate': {
    name: '[cn]Fate/stay night [Unlimited Blade Works]',
    prefixes: ['[cn]FS'],
    latestReleaseDate: '2026-05-29',
  },
  '[cn]rsa': {
    name: '[cn]蕾斯莱莉娅娜的炼金工房 ～忘却的炼金术与极夜的解放者～',
    prefixes: ['[cn]RSA'],
    latestReleaseDate: '2025-08-15',
  },
  '[cn]stg': {
    name: '[cn]STEINS;GATE',
    prefixes: ['[cn]STG'],
    latestReleaseDate: '2026-01-30',
  },
  '[cn]ccs': {
    name: '[cn]魔卡少女樱透明牌篇',
    prefixes: ['[cn]CCS'],
    latestReleaseDate: '2019-04-26',
  },
  '[cn]gu': {
    name: '[cn]请问您今天要来点兔子吗？',
    prefixes: ['[cn]GU'],
    latestReleaseDate: '2025-04-25',
  },
  '[cn]sao': {
    name: '[cn]刀剑神域',
    prefixes: ['[cn]SAO', '[cn]Gso'],
    latestReleaseDate: '2025-05-30',
  },
  '[cn]dgk': {
    name: '[cn]电击文库',
    prefixes: [
      '[cn]G86',
      '[cn]Gas',
      '[cn]Gaw',
      '[cn]Gbb',
      '[cn]Gbc',
      '[cn]Gbd',
      '[cn]Gbl',
      '[cn]Gby',
      '[cn]Gc3',
      '[cn]Gdc',
      '[cn]Gdr',
      '[cn]Gds',
      '[cn]Gdy',
      '[cn]Gem',
      '[cn]Gfq',
      '[cn]Gga',
      '[cn]Ggh',
      '[cn]Ggg',
      '[cn]Ggu',
      '[cn]Ghh',
      '[cn]Ghm',
      '[cn]Gid',
      '[cn]Giy',
      '[cn]Gkb',
      '[cn]Gkl',
      '[cn]Gkm',
      '[cn]Glt',
      '[cn]Gmf',
      '[cn]Gmm',
      '[cn]Gmr',
      '[cn]Gms',
      '[cn]Gnh',
      '[cn]Gnm',
      '[cn]Gns',
      '[cn]Gny',
      '[cn]Goi',
      '[cn]Gok',
      '[cn]Gom',
      '[cn]Gos',
      '[cn]Grk',
      '[cn]Gsb',
      '[cn]Gsc',
      '[cn]Gsd',
      '[cn]Gsk',
      '[cn]Gso',
      '[cn]Gsp',
      '[cn]Gsr',
      '[cn]Gss',
      '[cn]Gtd',
      '[cn]Gyf',
    ],
    latestReleaseDate: '2025-11-28',
  },
  '[cn]bd': {
    name: '[cn]BanG Dream!',
    prefixes: ['[cn]BD', '[cn]BDY'],
    latestReleaseDate: '2025-10-10',
  },
  '[cn]dal': {
    name: '[cn]约会大作战',
    prefixes: ['[cn]DAL'],
    latestReleaseDate: '2024-07-12',
  },
  '[cn]lrc': {
    name: '[cn]莉可丽丝',
    prefixes: ['[cn]LRC'],
    latestReleaseDate: '2024-08-23',
  },
  '[cn]nik': {
    name: '[cn]胜利女神：妮姬',
    prefixes: ['[cn]NIK'],
    latestReleaseDate: '2025-07-25',
  },
  '[cn]smp': {
    name: '[cn]Summer Pockets',
    prefixes: ['[cn]SMP'],
    latestReleaseDate: '2025-07-18',
  },
  '[cn]btr': {
    name: '[cn]孤独摇滚',
    prefixes: ['[cn]BTR'],
    latestReleaseDate: '2025-02-21',
  },
  '[cn]hbr': {
    name: '[cn]炽焰天穹',
    prefixes: ['[cn]HBR'],
    latestReleaseDate: '2024-12-20',
  },
  '[cn]kgl': {
    name: '[cn]辉夜大小姐想让我告白～天才们的恋爱头脑战～',
    prefixes: ['[cn]KGL'],
    latestReleaseDate: '2024-05-31',
  },
  '[cn]rsl': {
    name: '[cn]少女☆歌剧 Revue Starlight',
    prefixes: ['[cn]RSL'],
    latestReleaseDate: '2024-03-29',
  },
  '[cn]lnj': {
    name: '[cn]Love Live! 虹咲学园学园偶像同好会',
    prefixes: ['[cn]LNJ'],
    latestReleaseDate: '2024-10-25',
  },
  '[cn]isc': {
    name: '[cn]偶像大师 闪耀色彩',
    prefixes: ['[cn]ISC'],
    latestReleaseDate: '2025-09-19',
  },
  'wsc': {
    name: '其他',
    prefixes: ['[cn]WS', '[cn]CGS'],
    latestReleaseDate: '-',
  },
}

export const seriesMap = {
  ...Object.fromEntries(
    Object.entries(wsSeriesMap).map(([id, v]) => [id, { ...v, id, game: 'ws' }])
  ),
  ...Object.fromEntries(
    Object.entries(wsrSeriesMap).map(([id, v]) => [id, { ...v, id, game: 'wsr' }])
  ),
  ...Object.fromEntries(
    Object.entries(wscSeriesMap).map(([id, v]) => [id, { ...v, id, game: 'wsc' }])
  ),
}

export const ALL_SERIES_OPTIONS = Object.entries(seriesMap)
  .filter(([id]) => !['ws', 'wsr', 'wsc'].includes(id))
  .map(([id, info]) => ({
    title: info.name.replace('[cn]', ''),
    value: id,
    game: info.game,
  }))

export const GAME_TYPE_OPTIONS = [
  { title: 'WS', value: 'ws', color: 'primary' },
  { title: 'WSR', value: 'wsr', color: 'ws-rose' },
  { title: 'WSC', value: 'wsc', color: 'ws-cn' },
]
